# 1A

In [1]:
import numpy as np
arr = np.random.randint(1, 21, size=15)
print("Original Array:", arr)

reshaped = arr.reshape(3, 5)
print("\nReshaped Array (3x5):\n", reshaped)

print("\nShape of reshaped array:", reshaped.shape)

for i in range(reshaped.shape[0]):
    row_max_index = np.argmax(reshaped[i])
    reshaped[i][row_max_index] = 0

print("\nModified Array with row max replaced by 0:\n", reshaped)

Original Array: [ 1 12  3 17 19 10  9 13  2 13  2 18 16 12  8]

Reshaped Array (3x5):
 [[ 1 12  3 17 19]
 [10  9 13  2 13]
 [ 2 18 16 12  8]]

Shape of reshaped array: (3, 5)

Modified Array with row max replaced by 0:
 [[ 1 12  3 17  0]
 [10  9  0  2 13]
 [ 2  0 16 12  8]]


1B

In [2]:
array_2d = np.zeros((4, 3), dtype=np.int32)
print("2D Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Type:", type(array_2d))
print("Data type:", array_2d.dtype)

2D Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


1C

In [3]:
from numpy.linalg import eig

matrix = np.array([[3, -2],
                   [1,  0]])

values, vectors = eig(matrix)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# 1D

In [4]:
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

diagonal_sum = np.trace(array)
print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


# 1E

In [5]:
original = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

reshaped = original.reshape(2, 3)
print("Reshaped to 2x3:\n", reshaped)

Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
